#!/usr/bin/env python3
"""Entry point: read sources/, run the pipeline, write whitelist.txt.

Usage:
    python scripts/build.py --out whitelist.txt

For each sources/*.yaml file:
  1. Read the YAML
  2. Fetch the configured URL
  3. Dispatch to the configured parser
  4. Validate each candidate domain (lint)
  5. Resolve each candidate domain (DNS); drop unresolvable
  6. Emit the section in `output_section` order

The final file is deterministic: sections sorted alphabetically by
output_section, entries within each section sorted alphabetically.
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

import yaml

from scripts.lib import fetch as fetch_mod
from scripts.lib import resolve as resolve_mod
from scripts.lib.lint import ValidationError, validate_domain

PARSERS_DIR = Path(__file__).parent / "lib" / "parsers"
sys.path.insert(0, str(PARSERS_DIR.parent.parent))


def _import_parser(name: str):
    """Import a parser module by name (e.g. 'json_endpoint')."""
    import importlib

    return importlib.import_module(f"scripts.lib.parsers.{name}")


def _format_section(service: str, source_url: str, domains: list[str]) -> str:
    lines = [
        f"# === {service} ===",
        f"# Source: {source_url}",
    ]
    lines.extend(f"@@||{d}^\n" for d in domains)
    return "\n".join(lines) + "\n"


def _load_sources(sources_dir: Path) -> list[dict]:
    out = []
    for path in sorted(sources_dir.glob("*.yaml")):
        with path.open() as f:
            out.append(yaml.safe_load(f))
    return out


def _gather_section(cfg: dict, cache_dir: Path | None) -> list[str]:
    parser_name = cfg["fetch"]["type"]
    parser = _import_parser(parser_name)
    url = cfg["fetch"]["url"]
    payload = fetch_mod.fetch_url(url, cache_dir=cache_dir)
    candidates = parser.parse(payload, cfg["fetch"])

    valid: list[str] = []
    for cand in candidates:
        cand = cand.strip().lower().lstrip(".")
        try:
            validate_domain(cand)
        except ValidationError as e:
            print(f"  drop (lint): {cand}: {e}", file=sys.stderr)
            continue
        try:
            resolve_mod.resolve_domain(cand)
        except resolve_mod.ResolutionError as e:
            print(f"  drop (resolve): {cand}: {e}", file=sys.stderr)
            continue
        valid.append(cand)
    return sorted(set(valid))


def build_whitelist(sources_dir: Path, cache_dir: Path | None = None) -> str:
    """Render the full whitelist text from `sources_dir`.

    Args:
        sources_dir: Directory containing one YAML per service.
        cache_dir: If provided, vendor responses are cached here.

    Returns the full whitelist as a string.
    """
    sources = _load_sources(sources_dir)
    sources.sort(key=lambda c: c.get("output_section", c["service"]))

    today = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d")
    header = (
        "# dns-whitelist — AdGuard Home allowlist\n"
        "# Generated by scripts/build.py. Do not edit by hand.\n"
        f"# Last refreshed: {today} (UTC)\n"
        "# See README.md for usage.\n"
        "\n"
    )

    body_parts: list[str] = []
    for cfg in sources:
        print(f"Building: {cfg['service']}", file=sys.stderr)
        domains = _gather_section(cfg, cache_dir=cache_dir)
        body_parts.append(_format_section(
            cfg.get("output_section", cfg["service"]),
            cfg["source_url"],
            domains,
        ))

    return header + "\n".join(body_parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sources", type=Path,
                        default=Path(__file__).parent.parent / "sources")
    parser.add_argument("--out", type=Path,
                        default=Path(__file__).parent.parent / "whitelist.txt")
    parser.add_argument("--cache-dir", type=Path,
                        default=Path(__file__).parent.parent / ".cache")
    args = parser.parse_args()

    text = build_whitelist(sources_dir=args.sources, cache_dir=args.cache_dir)
    args.out.write_text(text)
    print(f"Wrote {args.out} ({len(text)} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
